server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 119.23.238.27
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://119.23.238.27:8760/eureka/
  server:
     enable-self-preservation : false
     eviction-interval-timer-in-ms : 30000
spring:
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/LiangCan/config
#          username: LiangCan123456
#          password: A4562880